#!/usr/bin/env zsh
# Improved version to forcefully override existing stow folders

pushd $DOTFILES || exit 1

# Convert comma-separated list into an array
folders=("${(@s/,/)STOW_FOLDERS}")

for folder in "${folders[@]}"; do
    echo "Restowing $folder"
    stow -R "$folder" || echo "Failed to restow $folder."
done

popd || exit 1

